### ISSUE TITLE
Possible Scripting Layer Support

### ISSUE THREAD

**Issue by odiminox** [praydog/RE2-Mod-Framework#24]
@praydog What are your thoughts on having a scripting layer with bindings to the C++ to massively help facilitate the development of RE:2 mods?

Possibilities such as Lua/Angel Script/C#.

If we lower the level of complexity required to leverage the capabilities of this framework via a scripting language interface, we might foster a broader community for modding of RE:2.

**Comment by praydog** [comment]
Sure, I think it would be suitable once the project maps out the RE Engine in a broader sense than it is right now. There could be more ways hiding within the engine to easily facilitate automatic bindings. The game uses C++/CLI or something so that could probably be leveraged somehow.

For now, I think this project should be turned into a C++ mod loader until then, or do what Kanan is doing where popular mods are integrated as pull requests.

**Comment by odiminox** [comment]
Sounds good; keep the scripting layer bindings separate and the project focused
