### ISSUE TITLE
Request : same thing for re resistance?

### ISSUE THREAD

**Issue by shinelucid** [praydog/RE2-Mod-Framework#60]
this mod has become the official thing for me i don't care anymore can you please make this for resistance please?

**Comment by HaveDex** [comment]
https://github.com/praydog/RE2-Mod-Framework/issues/57
praydog commented on May 31
@Zer01neDev, it's not. You need to start the game in DX11 mode for this to work.

And to answer the original question, no. Adding REsistance support to this would basically allow people to make cheats for it.


How does that make any sense? People are cheating left and right inside REsistance anyway. Even I use fucking cheat engine for some stuff.

"Oh no, let's not add this amazing, but slightly wonky fps mod to this game because some guy could freecam... around the map? and spot Yorick the security zombie? oh no, that's terrible."

Like I get where praydog is coming from, but that's naive holy shit. At least give us a better reason like saying "it would break every update anyway so it's not worth it". Saying you don't do it because people "might" cheat is just dumb and it shows you have no idea how fucked REsis is anyway. I can hop onto the game and cheat as much as I want and nothing will happen. I just would like to use first person and actually challenge myself by restricting movement and awareness. Anyone who wants to cheat doesn't need this mod framework. Yeah someone *could* make a cheat other than freecam out of it I guess, but who'd do that when you already have CE and advanced scripts that disable collision and can teleport people or kill them? Weak excuse, seriously. Fuck your codex brother.

**Comment by cursey** [comment]
> #57
> praydog commented on May 31
> @Zer01neDev, it's not. You need to start the game in DX11 mode for this to work.
> 
> And to answer the original question, no. Adding REsistance support to this would basically allow people to make cheats for it.
> 
> How does that make any sense? People are cheating left and right inside REsistance anyway. Even I use fucking cheat engine for some stuff.
> 
> "Oh no, let's not add this amazing, but slightly wonky fps mod to this game because some guy could freecam... around the map? and spot Yorick the security zombie? oh no, that's terrible."
> 
> Like I get where praydog is coming from, but that's naive holy shit. At least give us a better reason like saying "it would break every update anyway so it's not worth it". Saying you don't do it because people "might" cheat is just dumb and it shows you have no idea how fucked REsis is anyway. I can hop onto the game and cheat as much as I want and nothing will happen. I just would like to use first person and actually challenge myself by restricting movement and awareness. Anyone who wants to cheat doesn't need this mod framework. Yeah someone _could_ make a cheat other than freecam out of it I guess, but who'd do that when you already have CE and advanced scripts that disable collision and can teleport people or kill them? Weak excuse, seriously. Fuck your codex brother.

If you or anyone wanted to port this to REsistance they could do so without much trouble since all the reversing work has already been done for you. It's an open source project, if @praydog doesn't want to make it work for some multiplayer game because of how destructive it could be then that's entirely within their right. There's nothing naive about it, its their project, their choice. If you aren't happy with that decision just fork the project and do it yourself. You're not entitled to anything beyond what the chosen license states.

**Comment by HaveDex** [comment]
> > #57
> > praydog commented on May 31
> > @Zer01neDev, it's not. You need to start the game in DX11 mode for this to work.
> > And to answer the original question, no. Adding REsistance support to this would basically allow people to make cheats for it.
> > How does that make any sense? People are cheating left and right inside REsistance anyway. Even I use fucking cheat engine for some stuff.
> > "Oh no, let's not add this amazing, but slightly wonky fps mod to this game because some guy could freecam... around the map? and spot Yorick the security zombie? oh no, that's terrible."
> > Like I get where praydog is coming from, but that's naive holy shit. At least give us a better reason like saying "it would break every update anyway so it's not worth it". Saying you don't do it because people "might" cheat is just dumb and it shows you have no idea how fucked REsis is anyway. I can hop onto the game and cheat as much as I want and nothing will happen. I just would like to use first person and actually challenge myself by restricting movement and awareness. Anyone who wants to cheat doesn't need this mod framework. Yeah someone _could_ make a cheat other than freecam out of it I guess, but who'd do that when you already have CE and advanced scripts that disable collision and can teleport people or kill them? Weak excuse, seriously. Fuck your codex brother.
> 
> If you or anyone wanted to port this to REsistance they could do so without much trouble since all the reversing work has already been done for you. It's an open source project, if @praydog doesn't want to make it work for some multiplayer game because of how destructive it could be then that's entirely within their right. There's nothing naive about it, its their project, their choice. If you aren't happy with that decision just fork the project and do it yourself. You're not entitled to anything beyond what the chosen license states.

I have exactly 0 clue how to code or do anything along those lines. I know how to make some basic mods for source games and how to edit some other games' files like Dark Souls, but that's it.
If I knew how to port his fps mod to REsis I would've done it by now, I just don't know how to code and never will.
Call me lazy, but coding isn't my thing. As for him not wanting to port it, again he can do whatever he wants to. My point is his argument for not porting it is naive. There's no damage to be done, freecam would do nothing for REsistance outside of being able to fly around the second area and spot Yorick, the security zombie, from the get-go. Would definitely benefit some players, but wanna know what else benefits players? Cheat engine scripts that you can make yourself or download online. Again if he doesn't wanna work on it, because he feels like it's not worth it to update it once a month or he simply doesn't care about the mp mode I can understand it, but saying it's because "muh malicious cheats" is dumb plain and simple.
The only possible thing that could come out of this would be "cheat" that would be barely worth using. If I wanna win I just lag people out of the game or use infinite ammo/health as survivor while fucking with the timer as well or simply noclipping out of the match and touching the exit gate. Not a single person would use the mod to spot Yorick, because if someone wants to cheat they'll cheat the right way. To me it's just sad that he uses nonsense arguments instead of saying "I don't give a shit about your dumb game".

**Comment by 0P3N50URC3-F0R3V3R** [comment]
Who the hell cares that this would be enable cheating? XD It is dead anyways.  It is made Dead. I literally was enthusiastic when i bought that game on steam and it was a wreck since the beginning... No anticheat, full of exploters ect ect... and as capcom stands right now, neve will be fixed or supported as of.. .EVER...?  All we do for example, are playing with friends on lan. (Yes it is possible to do with opensource tools :P ALL features works with it) the vr/fps mod would be nice either way for private parties... it is more immersive... i dont think that this tool would further ruin a game that community/support/peoples is in a state as an ocean liner on the bottom of the sea...  This game is good but only with private parties thats all... XD I dont think that this tool would harm anyone, anyway; since on steam; the game basicly dead anyways. (See that other resident evil game that was avaliable back then... what was its title... it was strict multiplayer too, tps shooter that was so bad, that it was DOA also XD At least this one has some potantiel, even if not on public. )
